[project]
name = "video-generation-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.2",
    "python-multipart>=0.0.20",
    "requests>=2.32.5",
    "uvicorn>=0.23.2",
]
